site_name: MkLorum
site_url: https://example.com
nav:
    - Home: index.md
    - About: about.md
features:
  - navigation.instant
  - header.autohide
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
